version: 2
updates:
  # TypeScript dependency updates
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  # Kotlin dependency updates
  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: "weekly"

  # CocoaPods dependency updates
  - package-ecosystem: "cocoapods"
    directory: "/ios"
    schedule:
      interval: "weekly"
